import type { BudgetRepository } from '../budgetRepository';
import {
  createId,
  deleteMonthlyCategoryBudget,
  deleteShoppingBudgetCategory,
  deleteShoppingBudgetItem,
  deleteShoppingBudgetPlan,
  getAllMonthlyCategoryBudgets,
  getMonthlyCategoryBudgets,
  getShoppingBudgetCategories,
  getShoppingBudgetItems,
  getShoppingBudgetPlans,
  replaceAllMonthlyCategoryBudgets,
  replaceAllShoppingBudgetCategories,
  replaceAllShoppingBudgetItems,
  replaceAllShoppingBudgetPlans,
  replaceMonthlyCategoryBudgets,
  saveMonthlyCategoryBudget,
  saveMonthlyCategoryBudgets,
  saveShoppingBudgetCategories,
  saveShoppingBudgetCategory,
  saveShoppingBudgetItem,
  saveShoppingBudgetItems,
  saveShoppingBudgetPlan,
  saveShoppingBudgetPlans,
} from '../../utils/budgetStorage';

export const localBudgetRepository: BudgetRepository = {
  createId,
  deleteMonthlyCategoryBudget,
  deleteShoppingBudgetCategory,
  deleteShoppingBudgetItem,
  deleteShoppingBudgetPlan,
  getAllMonthlyCategoryBudgets,
  getMonthlyCategoryBudgets,
  getShoppingBudgetCategories,
  getShoppingBudgetItems,
  getShoppingBudgetPlans,
  replaceAllMonthlyCategoryBudgets,
  replaceAllShoppingBudgetCategories,
  replaceAllShoppingBudgetItems,
  replaceAllShoppingBudgetPlans,
  replaceMonthlyCategoryBudgets,
  saveMonthlyCategoryBudget,
  saveMonthlyCategoryBudgets,
  saveShoppingBudgetCategories,
  saveShoppingBudgetCategory,
  saveShoppingBudgetItem,
  saveShoppingBudgetItems,
  saveShoppingBudgetPlan,
  saveShoppingBudgetPlans,
};
